server:
  port: 9090
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: shweta@7448
    url: jdbc:postgresql://localhost:5432/RESTPOC2
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
